Django 3 By Example-Book/Bookmark App/account/urls.py
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import user_login, dashboard, register, edit

urlpatterns = [
    # path('login/', user_login, name='login')
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),

    # change password urls
    # path('password_change/',PasswordChangeView.as_view(),name='password_change'),
    # path('password_change/done/',PasswordChangeDoneView.as_view(),name='password_change_done'),
    
    # reset password urls
    # path('password_reset/',PasswordResetView.as_view(),name='password_reset'),
    # path('password_reset/done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # path('reset/done/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # above all path or url include it by default
    path('', include('django.contrib.auth.urls')),
    
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),

    path('', dashboard, name='dashboard'),
]

Django 3 By Example-Book/Bookmark App/core_project/urls.py
""" Core Project Urls """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django 3 By Example-Book/Bookmark App/images/urls.py
from django.urls import path
from .views import image_create, image_detail, image_like, image_list

app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',image_detail, name='detail'),
    path('like/', image_like, name='like'),
    path('', image_list, name='list'),
]

Django 3 By Example-Book/Bookmark App/account/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'

Django 3 By Example-Book/Bookmark App/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username         = forms.CharField()
    password         = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

from .models import Profile
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

Django 3 By Example-Book/Bookmark App/account/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm

from .models import Profile
from django.contrib import messages

# Create your views here.


@login_required
def dashboard(request):
    context = {'section': 'dashboard'}
    return render(request, 'account/dashboard.html', context)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, 'account/login.html', context)

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            context = {'new_user': new_user}
            return render(request,'registration/register_done.html', context)
    else:
        user_form = UserRegistrationForm()
    context = {'user_form': user_form}
    return render(request,'registration/register.html', context)

@login_required
def edit(request):
    if request.method == 'POST':
        user_form    = UserEditForm(instance=request.user,data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                        data=request.POST,
                                        files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # not in book (python 3 by example) but I found in django document
            messages.success(request, 'Profile details updated.')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form       = UserEditForm(instance=request.user)
        profile_form    = ProfileEditForm(instance=request.user.profile)

    context = {'user_form': user_form, 'profile_form': profile_form}

    return render(request,'registration/edit.html', context)

Django 3 By Example-Book/Bookmark App/account/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Local css -->
   <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>

    {% include 'navbar.html' %}
    
    {% block content %}

    {% endblock %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

    <script>

      var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
      });

      $(document).ready(function(){
          {% block domready %}
          {% endblock %}
      });
    </script>

  </body>
</html>

Django 3 By Example-Book/Bookmark App/account/templates/navbar.html
{% load static %}
<!-- As a heading -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
    <div class="container">
        <a class="navbar-brand mb-0 h1" href="{% url 'dashboard' %}">Social Website</a>

        {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">My dashboard</a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link" href="{% url 'images:list' %}">Images</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">People</a>
                </li>
            </ul>
        {% endif %}
        <ul class="navbar-nav justify-content-end">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-white text-bold" href="#">Hello {{ request.user.username|title }},</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Sign up</a>
                </li>
            {% endif %}
        </ul>

        <!-- <span>
            {% if request.user.is_authenticated %}
                Hello {{ request.user.username|title }},
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Log-in</a>
            {% endif %}
        </span> -->
    </div>
</nav>